project:
  type: website
  output-dir: docs

website:
  title: "Vincent Cotnoir"
  navbar:
    right:
      - href: index.qmd
        text: Présentation
      - href: cv.qmd
        text: CV
        
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

