project:
  type: website
  output-dir: docs
  preview: 
    timeout: 60

website:
  title: "Vincent Cotnoir.com"
  #possible d'ajouter about: pour avoir un template spécial 
  navbar:
    left:
      - href: index.qmd
        text: Présentation
      - href: cv.qmd
        text: CV
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/vincentcotnoir/
      - icon: github
        href: https://github.com/vcotnoir
  sidebar:
    search: true
        
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

