---
title: "Curriculum Vitae"
---

## **Vincent Cotnoir, CPA** {.test}

::: {.contact layout-ncol="2"}
[{{< fa brands linkedin size=2xl >}}](https://www.linkedin.com/in/vincentcotnoir/)<br>LinkedIn

{{< fa envelope size=Large >}}<br>cotnoir.vincent@gmail.com
:::

::: column-body-outset
::: panel-tabset
#### Francais

### **Éducation** {.test2}

**HEC Montréal**, Montréal<br> Maîtrise en intelligence d'affaires (fin prévue décembre 2023)

**Université de sherbrooke**, Sherbrooke<br> D.E.S.S. en expertise comptable, réussite de l'EFC (Septembre 2019)

**Université de sherbrooke**, Sherbrooke<br> Baccalauréat en administration, concentration en comptabilité

### **Expériences de travail** {.test2}

**Danone Canada**, Montreal<br> 
*Finance manager, Financial planning and analysis*<br>
*Avril 2021 - Août 2022*<br>

-   Consolidation des données marketing et des couts fixes<br>
-   Analyse des données financières pour assurer l'alignement avec l'entreprise<br>
-   Création d'outils de suivit des couts pour la haute direction<br>

**PriceWaterhouseCoopers Canada**, Montréal<br> 
*Analyste sénior, Certification*<br>
*Aout 2020 - Avril 2021*<br>

-   Planification de l'audit en effectuant l'évaluation des priorités et l'affectation des tâches<br>
-   Entretien de relations client collaboratives permettant la résolution des requêtes de l'équipe<br>
-   Encadrement des analystes par rétrospections constructives contribuant à leur développement<br>

**PriceWaterhouseCoopers Canada**, Montréal<br> 
*Analyste expérimenté, Certification*<br>
*Oct. 2019 - Août 2020*<br>

-   Comprendre et exécuter efficacement des sections complexes de l'audit (investissement, CMV)<br>
-   valuer les processus de contrôle favorisant la productivité de la stratégie du mandat<br>
-   Expliquer les écarts dans les états financiers d'une multitude d'entreprises<br>

### **Expériences parascolaires** {.test2}
**Comité Organisateur - Jeux du commerce 2018**, Montréal<br> 
*VP relations interuniversitaires*<br>
*Jan. 2017 - Avril 2018*

-   Maintenir une communication continue avec les 13 universités participantes via plusieurs canaux<br>
-   Résoudre les différends entre diverses parties prenantes assurant une compétition équitable<br>
-   Animer les tables de discussion pour informer du déroulement de la compétition<br>

### **Languages de programmation** {.test2}
-   SQL
-   R/Quarto (utilisé pour ce site avec Github)
-   SAS
-   Base de python

### **Compétences et intérêts** {.test2}
**Langues maitrisées:** Français et anglais<br>
**Outils de travail:** Suite Office, SAP, Alteryx, base de Tableau<br>
**Intérêts:** Cyclisme, Technologie de l'information, finance personnelle, Formule 1<br>
**Autres implications:**Comité Centraide PwC, Jeux du Commerce 2016 à 2019, Happening Marketing 2016 et 2017, Omnium Financier 2018 et Symposium GRH 2019

#### English

### **Education** {.test2}

**HEC Montreal**, Montreal<br> Business Intelligence masters (ending december 2023)

**Université de sherbrooke**, Sherbrooke<br> Accounting post-graduate diploma (D.E.S.S), CFE passed (September 2019)

**Université de sherbrooke**, Sherbrooke<br> BComm, accounting

### **Work experience** {.test2}

**Danone Canada**, Montreal<br> 
*Finance manager, Financial planning and analysis*<br>
April 2021 - Aug. 2022<br>
-   Consolidation of marketing and overhead financial data<br>
-   Financial data analysis to ensure alignement with business goals<br>
-   Creation of tool to ensure appropriate reflectio of costs to upper management<br>

**PriceWaterhouseCoopers Canada**, Montreal<br> 
*Senior analyst, Audit*<br>
Aug. 2020 - April 2021<br>

-   Audit planning and assessment of priorities throughout the team<br>
-   Collaborative client relationship management to ensure resolution of team requests<br>
-   Assess work of junior analysts and ensure that contructive feedback is given at opportunate moments<br>

**PriceWaterhouseCoopers Canada**, Montreal<br> 
*Experienced analyst, Audit*<br>
Oct. 2019 - Aug. 2020<br>

-   Understand and execute complex parts of the audit (investments, COGS)<br>
-   Evaluate control processes while ensure effective application of audit strategy<br>
-   Explain financial statement differences from multiple enterprises<br>

### **Extracurricular** {.test2}
**Organising committee - Jeux du commerce 2018**, Montréal<br> 
*VP university relations*<br>
Jan. 2017 - April 2018

-   Keep consistent communication with 13 universities through multiple channels<br>
-   Resolve problems between different parties while insuring a fair competition<br>
-   Entertain discussion tables to inform universities of competition details<br>

### **Programming languages** {.test2}

-   SQL
-   R/Quarto (used for this site with Github)
-   SAS
-   Basis in Python

### **Competencies and interests** {.test2}
**Languages:** French and english<br>
**Work Tools:** Office suite, SAP, Alteryx, Tableau basis<br>
**Interests:** Cycling, information technology, personnal finance, Formula 1 <br>
**Other extracurriculars:** PwC Centraide committee , Jeux du Commerce 2016 to 2019, Happening Marketing 2016 and 2017, Financial open 2018 and Symposium GRH 2019
:::
:::
